namespace Editor;

using Editor;
using Sandbox;
using Sandbox.UI;
using System.Collections.Generic;

public static partial class EditorToolBars
{
	// --- MAIN TOOL DEFINITIONS ---

	private static readonly List<ToolOptionDef> MainToolDefs =
	[
		new() { Name="Select",
			Icon="hammer/select_tool_icon.png",
			ToggledIcon="hammer/select_tool_icon_activated.png",
			Hotkey="Shift+S",
			Group = "MainTools",
			GroupType = ToolBarOptionGroupType.SingleExclusive,
			Checkable=true,
			Description="Select. Select groups, objects or mesh components",
			Active = true },

		new() { Name="Move",
			ShortcutAction = "tools.position-tool",
			Icon="hammer/move_tool_icon.png",
			ToggledIcon="hammer/move_tool_icon_activated.png",
			Hotkey="",
			Group = "MainTools",
			GroupType = ToolBarOptionGroupType.SingleExclusive,
			Checkable=true,
			Description="Translate. Move the selected objects" },
	
		new() { Name="Rotate",
			ShortcutAction = "tools.rotate-tool",
			Icon="hammer/rotate_tool_icon.png",
			ToggledIcon="hammer/rotate_tool_icon_activated.png",
			Hotkey="",
			Group = "MainTools",
			GroupType = ToolBarOptionGroupType.SingleExclusive,
			Checkable=true,
			Description="Rotate. Rotate the selected objects" },

		new() { Name="Scale",
			ShortcutAction = "tools.scale-tool",
			Icon="hammer/scale_tool_icon.png",
			ToggledIcon="hammer/scale_tool_icon_activated.png",
			Hotkey="",
			Group = "MainTools",
			GroupType = ToolBarOptionGroupType.SingleExclusive,
			Checkable=true,
			Description="Scale. Scale the selected objects" },

		new() { Name="Pivot",
			Icon="hammer/pivot_tool_icon.png",
			ToggledIcon="hammer/pivot_tool_icon_activated.png",
			Hotkey="",
			Group = "MainTools",
			GroupType = ToolBarOptionGroupType.SingleExclusive,
			Checkable=true,
			Description="Pivot Manipulation. Set the location of the gizmo for the current selection" },

		new() { Separator=true },
		new() { Separator=true },
		new() { Separator=true },

		new() { Name="Object Placer",
			Icon="hammer/entity_tool_icon.png",
			ToggledIcon="hammer/entity_tool_icon_activated.png",
			Hotkey="Shift+E",
			Group = "MainTools",
			GroupType = ToolBarOptionGroupType.SingleExclusive,
			Checkable=true,
			Description="Add new objects to the scene" },

		new() { Name="Block Tool",
			ShortcutAction = "tools.block-tool",
			Icon="hammer/block_tool_icon.png",
			ToggledIcon="hammer/block_tool_icon_activated.png",
			Hotkey="Shift+B",
			Group = "MainTools",
			GroupType = ToolBarOptionGroupType.SingleExclusive,
			Checkable=true,
			Description="Create new shapes by dragging out a box" },

		new() { Name="Path Tool",
			Icon="hammer/path_tool_icon.png",
			ToggledIcon="hammer/path_tool_icon_activated.png",
			Hotkey="Shift+P",
			Group = "MainTools",
			GroupType = ToolBarOptionGroupType.SingleExclusive,
			Checkable=true,
			Description="Create path entities or primitives" },

		new() { Name="Polygon Tool",
			Icon="hammer/polygon_tool_icon.png",
			ToggledIcon="hammer/polygon_tool_icon_activated.png",
			Group = "MainTools",
			GroupType = ToolBarOptionGroupType.SingleExclusive,
			Checkable=true,
			Description="Draw a polygon mesh" },

		new() { Name="Clipping Tool",
			Icon="hammer/clipping_tool_icon.png",
			ToggledIcon="hammer/clipping_tool_icon_activated.png",
			Hotkey="Shift+X",
			Group = "MainTools",
			GroupType = ToolBarOptionGroupType.SingleExclusive,
			Checkable=true,
			Description="Slice the selection by a plane" },

		new() { Name="Mirror Tool",
			Icon="hammer/mirror_tool_icon.png",
			ToggledIcon="hammer/mirror_tool_icon_activated.png",
			Hotkey="Shift+F",
			Group = "MainTools",
			GroupType = ToolBarOptionGroupType.SingleExclusive,
			Checkable=true,
			Description="Mirror the selection" },

		new() { Name="Texture Projection Tool",
			Icon="hammer/textureprojection_tool_icon.png",
			ToggledIcon="hammer/textureprojection_tool_icon_activated.png",
			Group = "MainTools",
			GroupType = ToolBarOptionGroupType.SingleExclusive,
			Checkable=true,
			Description="Modify texture mapping using projection tools" },

		new() { Name="Blend Painting Tool",
			Icon="hammer/paint_tool_icon.png",
			ToggledIcon="hammer/paint_tool_icon_activated.png",
			Hotkey="Shift+V",
			Group = "MainTools",
			GroupType = ToolBarOptionGroupType.SingleExclusive,
			Checkable=true,
			Description="Paint vertex blends, weights and colors" },

		new() { Name="Displacement Tool",
			Icon="hammer/displacement_tool_icon.png",
			ToggledIcon="hammer/displacement_tool_icon_activated.png",
			Group = "MainTools",
			GroupType = ToolBarOptionGroupType.SingleExclusive,
			Checkable=true,
			Description="Modify subdivided faces using brush tools" },

		new() { Name="Physics Tool",
			Icon="hammer/physics_tool_icon.png",
			ToggledIcon="hammer/physics_tool_icon_activated.png",
			Group = "MainTools",
			GroupType = ToolBarOptionGroupType.SingleExclusive,
			Checkable=true,
			Description="Manipulate objects using physics simulation" },

		new() { Name="Terrain Tool",
			Icon="hammer/tool_terrain_icon.png",
			ToggledIcon="hammer/tool_terrain_icon_activated.png",
			Group = "MainTools",
			GroupType = ToolBarOptionGroupType.SingleExclusive,
			Checkable=true,
			Description="Create and modify terrain" },

		new() { Name="Asset Spray Tool",
			Icon="hammer/asset_spray_tool_icon.png",
			ToggledIcon="hammer/asset_spray_tool_icon_activated.png",
			Group = "MainTools",
			GroupType = ToolBarOptionGroupType.SingleExclusive,
			Checkable=true,
			Description="Place pre-configured groups of objects on to a surface with randomization" },

		new() { Name="Tile Editor Tool",
			Icon="hammer/tile_grid_tool_icon.png",
			ToggledIcon="hammer/tile_grid_tool_icon_activated.png",
			Group = "MainTools",
			GroupType = ToolBarOptionGroupType.SingleExclusive,
			Checkable=true,
			Description="Edit tiled surfaces" },

		new() { Name="Vertex Normal Paint",
			Icon="hammer/vertex_normal_paint.png",
			ToggledIcon="hammer/vertex_normal_paint_activated.png",
			Group = "MainTools",
			GroupType = ToolBarOptionGroupType.SingleExclusive,
			Checkable=true,
			Description="Paint vertex normals" },

		new() { Separator=true },
		new() { Separator=true },
	];

	// --- SELECTION MODE DEFINITIONS ---

	private static readonly List<ToolOptionDef> SelectionModeDefs =
	[
		new() { Name="Vertices",
			ShortcutAction = "mesh.vertex",
			Icon="hammer/selection_mode_vertices.png",
			ToggledIcon="hammer/selection_mode_vertices_activated.png",
			Hotkey="Vertex",
			Checkable=true,
			Group="SelectionMode",
			GroupType=ToolBarOptionGroupType.SingleExclusive,
			Description="Selection Mode: Vertices" },

		new() { Name="Edges",
			ShortcutAction = "mesh.edge",
			Icon="hammer/selection_mode_edges.png",
			ToggledIcon="hammer/selection_mode_edges_activated.png",
			Hotkey="Edge",
			Checkable=true,
			Group="SelectionMode",
			GroupType=ToolBarOptionGroupType.SingleExclusive,
			Description="Selection Mode: Edges" },

		new() { Name="Faces",
			ShortcutAction = "mesh.face",
			Icon="hammer/selection_mode_faces.png",
			ToggledIcon="hammer/selection_mode_faces_activated.png",
			Hotkey="Face",
			Checkable=true,
			Group="SelectionMode",
			GroupType=ToolBarOptionGroupType.SingleExclusive,
			Description="Selection Mode: Faces" },

		new() { Name="Meshes",
			ShortcutAction = "mesh.mesh",
			Icon="hammer/selection_mode_solids.png",
			ToggledIcon="hammer/selection_mode_solids_activated.png",
			Hotkey="Mesh",
			Checkable=true,
			Group="SelectionMode",
			GroupType=ToolBarOptionGroupType.SingleExclusive,
			Description="Selection Mode: Meshes" },

		new() { Name="Objects",
			ShortcutAction = "mesh.objects",
			Icon="hammer/selection_mode_objects.png",
			ToggledIcon="hammer/selection_mode_objects_activated.png",
			Hotkey="Object",
			Checkable=true,
			Group="SelectionMode",
			GroupType=ToolBarOptionGroupType.SingleExclusive,
			Description="Selection Mode: Objects",
			Active = true },

		new () { Name="Groups",
			Icon="hammer/selection_mode_groups.png",
			ToggledIcon="hammer/selection_mode_groups_activated.png",
			Hotkey="6",
			Checkable=true,
			Group="SelectionMode",
			GroupType=ToolBarOptionGroupType.SingleExclusive,
			Description="Selection Mode: Groups" },

		new() { Name="Navigation",
			ShortcutAction="tools.navmesh-tool",
			Icon="hammer/selection_mode_nav.png",
			ToggledIcon="hammer/selection_mode_nav_activated.png",
			Hotkey="8",
			Checkable=true,
			Group="SelectionMode",
			GroupType=ToolBarOptionGroupType.SingleExclusive,
			Description="Selection Mode: Navigation" },
	];

	// --- EDITING SETTINGS DEFINITIONS ---

	private static readonly List<ToolOptionDef> EditingSettingDefs =
	[
		new() { Name = "World Space",
			Icon = "hammer/coordinate_frame_world.png",
			ToggledIcon = "hammer/coordinate_frame_world_activated.png",
			Checkable = true,
			Description = "Use World Space Axes for Gizmo",
			Group = "3DTypeSpace",
			GroupType = ToolBarOptionGroupType.SingleExclusive,
			Active = true },

		new() { Name = "Local Space",
			Icon = "hammer/coordinate_frame_local.png",
			ToggledIcon = "hammer/coordinate_frame_local_activated.png",
			Checkable = true,
			Description = "Use Selection's Local Space Axes for Gizmo",
			Group = "3DTypeSpace",
			GroupType = ToolBarOptionGroupType.SingleExclusive },

		new() { Name = "Pick Workplane",
			Icon = "hammer/workplane_tool_icon.png",
			ToggledIcon = "hammer/workplane_tool_icon_activated.png",
			Checkable = true,
			Hotkey = "Shift+Q",
			Description = "Pick Workplane from objects and surfaces" },

		new() { Name = "Reset Workplane",
			Icon = "hammer/workplane_reset_icon.png",
			ToggledIcon = "hammer/workplane_reset_icon_activated.png",
			Hotkey = "Alt+Shift+Q",
			Checkable = false,
			GroupType = ToolBarOptionGroupType.ExternallyControlled,
			ConditionalOn = "Pick Workplane",
			Description = "Reset the workplane when custom workplane is active" },

		new() { Separator=true },

		new() { Name = "Texture Lock",
			Icon = "hammer/toggle_texture_lock_component.png",
			ToggledIcon = "hammer/toggle_texture_lock_component_activated.png",
			Checkable = true,
			Hotkey = "Ctrl+Shift+Y",
			Description = "Texture Lock" },

		new() { Name = "Texture Lock Scale",
			Icon = "hammer/toggle_texture_lock_scale.png",
			ToggledIcon = "hammer/toggle_texture_lock_scale_activated.png",
			Checkable = true,
			Description = "Texture Lock Scale" },

		new() { Name = "Texture Lock Component",
			Icon = "hammer/toggle_texture_lock_component.png",
			ToggledIcon = "hammer/toggle_texture_lock_component_activated.png",
			Checkable = true,
			Description = "Texture Lock Component Manipulations" },

		new() { Name = "Lasso Through",
			Icon = "hammer/toggle_select_through.png",
			ToggledIcon = "hammer/toggle_select_through_activated.png",
			Checkable = true,
			Hotkey = "Ctrl+Shift+L",
			Description = "Enable Lasso Select Through" },

		new() { Name = "Lasso Partial",
			Icon = "hammer/toggle_select_intersecting.png",
			ToggledIcon = "hammer/toggle_select_intersecting_activated.png",
			Checkable = true,
			Description = "Enable Lasso Select Partial Intersections" },

		new() { Name = "Backface Select",
			Icon = "hammer/toggle_select_backfacing.png",
			Checkable = true,
			Hotkey = "Ctrl+Shift+F9",
			Description = "Enable Backface Selection" },

		new() { Separator=true },
		new() { Separator=true },
		new() { Separator=true },

		new() { Name = "Run Game",
			Icon = "hammer/run_map.png",
			ToggledIcon = "hammer/run_map_activated.png",
			Hotkey = "F5",
			Description = "Run Game",
			Checkable = true,
			GroupType = ToolBarOptionGroupType.None
		},

		new() { Name = "Pause Game",
			Icon = "hammer/pause_map.png",
			ToggledIcon = "hammer/pause_map_activated.png",
			Hotkey = "F6",
			Description = "Pause Game",
			Checkable = true,
			GroupType = ToolBarOptionGroupType.ConditionalClearState,
			ConditionalOn = "Run Game"
		},

		new() { Name = "Eject",
			Icon = "hammer/eject.png",
			ToggledIcon = "hammer/eject_activated.png",
			Hotkey = "F7",
			Description = "Eject",
			Checkable = true,
			GroupType = ToolBarOptionGroupType.ConditionalClearState,
			ConditionalOn = "Run Game"
		},
	];

	// --- VIEW SETTINGS DEFINITIONS ---

	private static readonly List<ToolOptionDef> ViewSettingDefs =
	[
		new() { Name="Show Helpers",
			Icon="hammer/toggle_show_helpers.png",
			ToggledIcon="hammer/toggle_show_helpers_activated.png",
			Checkable=true,
			Hotkey="Ctrl+Shift+H",
			Description="Show Helpers" },

		new() { Name="Editor Objects",
			Icon="hammer/toggle_editor_objects.png",
			ToggledIcon="hammer/toggle_editor_objects_activated.png",
			Checkable=true,
			Hotkey="Shift+O",
			GroupType = ToolBarOptionGroupType.ConditionalPreserveState,
			Description="Show Editor Only Objects" },

		new() { Name="Tools Materials",
			Icon="hammer/toggle_tools_materials.png",
			ToggledIcon="hammer/toggle_tools_materials_activated.png",
			Checkable=true,
			Hotkey="Ctrl+Shift+F2",
			GroupType = ToolBarOptionGroupType.ConditionalPreserveState,
			ConditionalOn = "Editor Objects",
			Description="Show Tools Materials (disabled if Editor Objects is off)" },

		new() { Name="Force Lights On",
			Icon="hammer/toggle_force_lights_on.png",
			ToggledIcon="hammer/toggle_force_lights_on_activated.png",
			Checkable=true,
			Description="Force all lights to be on in the editor even if disabled in the game" },

		new() { Name="Visibility Contributors",
			Icon="hammer/toggle_vis_preview.png",
			ToggledIcon="hammer/toggle_vis_preview_activated.png",
			Checkable=true,
			Description="Hide objects and materials which do not contribute to vis" },

		new() { Name="Show Collision",
			Icon="hammer/toggle_collision_hulls.png",
			ToggledIcon="hammer/toggle_collision_hulls_activated.png",
			Checkable=true,
			Hotkey="Ctrl+Shift+F3",
			Description="Show Collision Models" },

		new() { Name="Selection Overlay",
			Icon="hammer/toggle_selection_overlay.png",
			ToggledIcon="hammer/toggle_selection_overlay_activated.png",
			Checkable=true,
			Hotkey="Ctrl+Shift+F4",
			Description="Toggle Selection Overlay" },

		new() { Name="Gray Out Instances",
			Icon="hammer/toggle_instance_overlay.png",
			ToggledIcon="hammer/toggle_instance_overlay_activated.png",
			Checkable=true,
			Hotkey="Ctrl+Shift+F5",
			Description="Gray Out Objects Outside Instance" },

		new() { Name="Mesh Subdivision",
			Icon="hammer/toggle_mesh_subdivision.png",
			ToggledIcon="hammer/toggle_mesh_subdivision_activated.png",
			Checkable=true,
			Hotkey="Ctrl+Shift+F6",
			Description="Toggle Mesh Subdivision" },

		new() { Name="Mesh Tiles 3D",
			Icon="hammer/toggle_mesh_tiles_3d.png",
			ToggledIcon="hammer/toggle_mesh_tiles_3d_activated.png",
			Checkable=true,
			Hotkey="Ctrl+Shift+F7",
			Description="Toggle Mesh Tiles in 3D View" },

		new() { Name="Mesh Tiles 2D",
			Icon="hammer/toggle_mesh_tiles_2d.png",
			ToggledIcon="hammer/toggle_mesh_tiles_2d_activated.png",
			Checkable=true,
			Hotkey="Ctrl+Shift+F8",
			Description="Toggle Mesh Tiles in 2D View" },

		new() { Name="Model Animation",
			Icon="hammer/toggle_model_animation.png",
			ToggledIcon="hammer/toggle_model_animation_activated.png",
			Checkable=true,
			Description="Toggle Model Animation" },

		new() { Name="Restart Particles",
			Icon="hammer/restart_particles.png",
			Checkable=false,
			Description="Restart the selected particle systems or all if none selected" },

		new() { Name="Particle Visibility",
			Icon="hammer/toggle_particles.png",
			ToggledIcon="hammer/toggle_particles_activated.png",
			Checkable=true,
			Description="Toggle Particle Visibility" },

		new() { Name="Toggle Grass",
			Icon="hammer/toggle_show_grass.png",
			ToggledIcon="hammer/toggle_show_grass_activated.png",
			Checkable=true,
			Description="Toggle Grass" },

		new() { Separator=true },

		new() { Name="Cycle View Distance",
			Icon="hammer/view_distance_short.png",
			IconCycle =
			[
				"hammer/view_distance_med_short.png",
				"hammer/view_distance_med.png",
				"hammer/view_distance_med_long.png",
				"hammer/view_distance_long.png",
				"hammer/view_distance_short.png"
			],          
			Description="Cycle View Distance",	
			Checkable=false, },
	];
}
